In [1]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd
import numpy as np
import pagerank_test

In [2]:
print(pagerank_test.A2)


           1     2     3     4     5     6
     -------------------------------------
 1  |  0.167 0.167 0.167 0.167 0.167 0.167
 2  |  0.167 0.167 0.167 0.167 0.167 0.167
 3  |  0.167 0.167 0.167 0.167 0.167 0.167
 4  |  0.167 0.167 0.167 0.167 0.167 0.167
 5  |  0.167 0.167 0.167 0.167 0.167 0.167
 6  |  0.167 0.167 0.167 0.167 0.167 0.167



In [2]:
import numpy as np
def find_num_links(link_mat):
    # returns a vector equal in length to columns of link_mat
    # each row in the vector is the sum of links in the corresponding column
    ones_vec = np.ones(link_mat.shape[0])
    return link_mat.T@ones_vec
    
sum_mat = np.array([[1,0,0,1,0,0],
                    [0,0,1,1,1,1],
                    [0,1,0,0,0,0],
                    [0,0,0,0,1,0],
                    [0,0,0,0,0,1],
                    [0,0,0,0,1,0]])

def make_markov(link_mat):
    num_links = find_num_links(link_mat)
    num_links_weights = 1/num_links
    diag_weights = np.diag(num_links_weights)
    A1_mat = link_mat@diag_weights
    return A1_mat

def power_method(markov_mat, num_iters):
    # don't use; this one has a hardcoded 6x6 matrix
    init_vec = np.ones(markov_mat.shape[1])
    A2_mat = np.full((6,6), 1/6)
    A = (.85*markov_mat) + (.15*A2_mat)
    output_vec = init_vec
    for i in range(num_iters):
        output_vec = A@output_vec
    return output_vec

def power_method_sparse(markov_mat, num_iters):
    init_vec = np.ones(markov_mat.shape[1])
    A2_val = 1/markov_mat.shape[0]
    output_vec = init_vec
    for i in range(num_iters):
        w = markov_mat@output_vec
        a2_adjust = .15 * output_vec.dot(np.full(len(output_vec), A2_val))
        output_vec = (.85*w) + a2_adjust
    return output_vec
    
markov_mat = make_markov(sum_mat)
print("Original markov mat")
print(markov_mat)
print(power_method(markov_mat, 20))
print(power_method_sparse(markov_mat, 20))

Original markov mat
[[1.         0.         0.         0.5        0.         0.        ]
 [0.         0.         1.         0.5        0.33333333 0.5       ]
 [0.         1.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.         0.5       ]
 [0.         0.         0.         0.         0.33333333 0.        ]]
[1.62008527 1.90067519 1.79851951 0.21885362 0.24301279 0.21885362]
[1.62008527 1.90067519 1.79851951 0.21885362 0.24301279 0.21885362]


In [3]:
from pageranker import PageRanker
from scipy.sparse import dok_matrix
from scipy.sparse import diags
import numpy as np
# titles_filename = "ch_12_support/titles.txt"
# inverse_titles_index_filename = "ch_12_support/inverseindex"
# word_index_filename = "ch_12_support/indexindex.txt"
# links_filename = "ch_12_support/links.bin"

# ranker = PageRanker(titles_filename, inverse_titles_index_filename, word_index_filename, links_filename)

test_links = dok_matrix([[1,0,0,1,0,0],
                        [0,0,1,1,1,1],
                        [0,1,0,0,0,0],
                        [0,0,0,0,1,0],
                        [0,0,0,0,0,1],
                        [0,0,0,0,1,0]])

markov_mat = PageRanker.make_markov(test_links)


new markov mat
[[1.         0.         0.         0.5        0.         0.        ]
 [0.         0.         1.         0.5        0.33333333 0.5       ]
 [0.         1.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.33333333 0.        ]
 [0.         0.         0.         0.         0.         0.5       ]
 [0.         0.         0.         0.         0.33333333 0.        ]]
[1.62008527 1.90067519 1.79851951 0.21885362 0.24301279 0.21885362]
new power method
[1.62008527 1.90067519 1.79851951 0.21885362 0.24301279 0.21885362]


In [64]:
%load_ext autoreload
from pageranker import PageRanker
%load_ext autoreload
from ch_12_support import pagerank
import struct
import array



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [65]:
page_rank_vec = PageRanker.compute_pagerank_vector(page_ranker)

Starting expensive set-up. This will take a bit.
Reading in wikipedia data from ./ch_12_support/links.bin
..................................................................................
Building map from title:position in vector
building full links matrix
Making links matrix markov...


/Users/luke.holoubek/Documents/coding_the_matrix/tasks/luke/pageranker.py:154: RuntimeWarning: divide by zero encountered in true_divide
  multiplied = link_mat@diag_mat


Computing power method on our markov matrix to get our pagerank'd eigenvector


In [73]:
%load_ext autoreload
from pageranker import PageRanker
titles_filename = "./ch_12_support/titles.txt"
inverse_titles_index_filename = "./ch_12_support/inverseindex"
word_index_filename = "./ch_12_support/indexindex.txt"
links_filename = "./ch_12_support/links.bin"

page_ranker = PageRanker(titles_filename, inverse_titles_index_filename, word_index_filename, links_filename)
page_ranker.page_rank_vec = page_rank_vec

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Building map from title:position in vector


In [96]:
results = page_ranker.query("math", num_results=50)
print(results)

[('mathematics', 509.37372827853164), ('city', 311.6207351250684), ('1995', 273.8398247459559), ('texas', 262.072617037924), ('economics', 223.22489620503322), ('massachusetts', 220.37511582787226), ('physics', 192.01408701027913), ('1964', 184.96137891702597), ('harvard university', 184.3294550594012), ('earth', 158.5311875200723), ('hawaii', 142.38663924994717), ('columbia university', 135.54557733564377), ('petroleum', 132.3893771075619), ('radio', 128.8881326652411), ('jesus', 125.16738133987806), ('yale university', 124.60398875178267), ('korea', 123.48623098615829), ('chemistry', 109.37097277526367), ('princeton university', 107.32988249881973), ('coal', 105.90147429928055), ('cornell university', 99.87561538489099), ('manhattan', 99.02191210670215), ('computer', 96.32631472798978), ('vermont', 95.28476810411364), ('mississippi', 93.57351018278912), ('encyclopdia britannica', 92.46715241244858), ('real number', 90.37897687271216), ('function (mathematics)', 84.9825571283797), ('e